#!/usr/bin/env python3
import sys
import os
import numpy as np
import matplotlib.pyplot as plt
from common import load_array, clip_array


def main():
    cmap = 'gray'
    clip_threshold = None
    # process command line arguments
    if len(sys.argv) >= 2:
        in_filename = sys.argv[1]
        if len(sys.argv) >= 3:
            clip_threshold = int(sys.argv[2])
            if len(sys.argv) >= 4:
                cmap = sys.argv[3]
    else:
        print("Usage: mplshow filename [threshold [colormap]]")
        sys.exit(1)

    init_arr = load_array(in_filename)
    clipped_arr = clip_array(init_arr, clip_threshold)
    rot_arr = np.fliplr(clipped_arr.T)  # rotate image right 90 degrees

    plt.imshow(rot_arr, cmap=cmap)
    plt.show()

    # write PNG image
    out_basename, _ = os.path.splitext(in_filename)
    out_filename = out_basename + ".png"
    print("writing PNG image to %s" % out_filename)
    plt.imsave(out_filename, rot_arr, cmap=cmap)


if __name__ == "__main__":
    main()
