#!/usr/bin/env python
import sys
import os
import numpy as np
from PIL import Image
from common import load_array, clip_array


def main():
    clip_threshold = None
    # process command line arguments
    if len(sys.argv) >= 2:
        in_filename = sys.argv[1]
        if len(sys.argv) >= 3:
            clip_threshold = int(sys.argv[2])
    else:
        print("Usage: pilshow filename [threshold]")
        sys.exit(1)

    init_arr = load_array(in_filename)
    clipped_arr = clip_array(init_arr, clip_threshold)

    # rescale to 255 levels of gray
    max_intensity = np.max(clipped_arr)
    rescaled_arr = 255.0 * clipped_arr / max_intensity

    # rotate image right 90 degrees
    rot_arr = np.fliplr(rescaled_arr.T)

    # display image momentarily
    img = Image.fromarray(rot_arr)
    img.show()

    # write PNG image
    out_basename, _ = os.path.splitext(in_filename)
    out_filename = out_basename + ".png"
    print("writing PNG image to %s" % out_filename)
    img_lum = img.convert("L")
    img_lum.save(out_filename)


if __name__ == "__main__":
    main()
